linters:
  enable-all: false
  disable-all: true
  enable:
    - govet
    - gofmt
    - revive
    - goimports
    - goconst
    - errcheck
    - exhaustive
    - exportloopref
    - deadcode
    - ifshort
    - ineffassign
    - unused
    - unconvert
    - unparam

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: context-keys-type
      - name: time-equal
      - name: if-return
      - name: superfluous-else
      - name: errorf
      - name: waitgroup-by-value
      - name: atomic
      - name: dot-imports
      - name: error-return

issues:
  exclude-use-default: false
