name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-code-analysis:
    name: 'Static Code analysis 🕵️‍♀️'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - name: Set up Go
        uses: actions/setup-go@v2
        with: { go-version: 1.17 }
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: unit testing
        if: matrix.os == 'ubuntu-latest'
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: unit testing
        if: matrix.os != 'ubuntu-latest'
        run: go test -v -race ./...
      - uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          name: codecov-glob
